[package]
name = "io_benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.5"
clap = { version = "3.1.2", features = ["derive"] }
libc = "0.2"
rand="0.3.14"